# Generated by Django 4.1 on 2022-08-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Force_HLG", "0033_auto_20220206_1435"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pretestmouseevent",
            name="clickedITMbr",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="pretestmouseevent",
            name="clickedITMtl",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
