# Generated by Django 4.1 on 2022-09-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0034_alter_pretestmouseevent_clickeditmbr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='energyEdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=25)),
                ('user', models.CharField(blank=True, max_length=100)),
                ('question', models.CharField(blank=True, max_length=25)),
                ('timeStamp', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='forceEdu',
        ),
        migrations.DeleteModel(
            name='forceLog',
        ),
        migrations.DeleteModel(
            name='forceMouseEvent',
        ),
        migrations.DeleteModel(
            name='vectorsEdu',
        ),
        migrations.DeleteModel(
            name='vectorsLog',
        ),
        migrations.DeleteModel(
            name='vectorsMouseEvent',
        ),
    ]
