# Generated by Django 4.1 on 2022-09-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0035_energyedu_delete_forceedu_delete_forcelog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyedu',
            name='timeStamp',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
