# Generated by Django 4.1.1 on 2022-09-19 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0037_alter_energyedu_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pretestLog',
        ),
        migrations.DeleteModel(
            name='pretestMouseEvent',
        ),
    ]
